version: '3.8'

services:
  app:
    container_name: 'selfcare-integration'
    image: ${image}
    build:
      dockerfile: Dockerfile
      context: ../
      secrets:
        - GH_TOKEN
    env_file:
      - ./.env
    ports:
      - "8080:8080"

secrets:
  GH_TOKEN:
    file: ./secrets
