version: '3.8'

services:
  app:
    container_name: 'selfcare-integration'
    image: ${image}
    build:
      dockerfile: Dockerfile
      context: ../
    env_file:
      - ./.env
    ports:
      - "8080:8080"
