apiVersion: v2
name: pagopa-api-config-selfcare-integration
description: Microservice that manages requests from selfcare
type: application
version: 1.0.1-2-PAGOPA-930-creare-per-le-ec-get-broker-id-stations
appVersion: 1.0.1-2-PAGOPA-930-creare-per-le-ec-get-broker-id-stations
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
