apiVersion: v2
name: pagopa-api-config-selfcare-integration
description: Microservice that manages requests from selfcare
type: application
version: 1.103.0
appVersion: 1.12.5-1-PIDM-487
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
# - name: microservice-chart
#   version: 2.8.0
#   repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
#   alias: oracle
#   condition: oracle.enabled
