microservice-chart:
  namespace: "apiconfig"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-api-config-selfcare-integration
    tag: "1.0.1-3-PAGOPA-930-creare-per-le-ec-get-broker-id-stations"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuprod.shared.internal.platform.pagopa.it"
    path: /pagopa-api-config-selfcare-integration/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaapiconfigselfcareintegration' # required to show cloud role name in application insights
    ENV: 'azure-prod'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '' #TODO
    SPRING_DATASOURCE_URL: '' #TODO
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    SPRING_DATASOURCE_USERNAME: '' #TODO
    SPRING_DATASOURCE_PASSWORD: 'oracle-db-cfg-password'
  keyvault:
    name: "pagopa-p-apiconfig-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  canaryDelivery:
    deployment:
      image:
        tag: 1.0.1-11-PAGOPA-930-creare-per-le-ec-get-broker-id-stations
