name: Integration Tests

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod
      deploy_uat:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false



jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: ${{( github.event.inputs == null && 'dev') || inputs.environment }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Run Integration Tests
        run: |
          cd ./integration-test
          export CUCUMBER_PUBLISH_TOKEN=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
          sh run_integration_test.sh ${{( github.event.inputs == null && 'dev') || inputs.environment }} ${{ secrets.SUBKEY }}

  deploy_aks:
    name: Deploy on AKS
    needs: [ test ]
    if: ${{ inputs.deploy_uat }}
    uses: ./.github/workflows/deploy_with_github_runner.yml
    with:
      environment: uat
      target: uat
    secrets: inherit
